### PR TITLE
Warn developer when a template-tag package is bad

### LINKED ISSUE #497: unknown pipeline package names in template tags fail silently
In pipeline/templatetags/pipeline.py , there's a decision to avoid emitting anything to the browser when an undefined package is requested, but it also doesn't warn the host or developer, which is bad.

### PR DESCRIPTION
**Pull request by chadmiller**
Fixes #497.

### CODE REVIEW

**Comment by cyberdelia** [comment]
Great idea, but maybe this should use a named logger or using warnings?

**Comment by chadmiller** [comment]
How's this?

**Comment by cyberdelia** [comment]
Looks good, merged in 988cf17e9ef7c6982c0ebdbc7740700cd0ff0f71

**Comment by cyberdelia** [comment]
Also, thanks again :bowtie:

**Pull request closed without merging**
